language: python

python:
- '3.5'

branches:
  only:
  - master
  - /^_gitz_stripe_.*$/

matrix:
  include:
    - python: 3.9-dev
      dist: xenial

install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
- pip install -r extract_nc/extract_requirements.txt

script:
- flake8 nc test
- pytest test
