language: python

python:
- '3.4'
- '3.5'
- '3.6'

matrix:
  include:
    - python: 3.7
      dist: xenial

install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
- pip install -r extract_requirements.txt

script:
- flake8 nc test
# - mypy nc test  # Doesn't work in Python 3.4
- pytest test
